apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: cluster-alerts
  namespace: monitoring
  labels:
    release: monitoring
spec:
  groups:
  - name: kubernetes.resources
    rules:
    - alert: NodeMemoryFilling
      #expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 85
      expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 15 # temp for test
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Заканчивается память на ноде {{ $labels.instance }}"
        description: "Узел {{ $labels.instance }} использует {{ $value }}% доступной памяти."