apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-contactpoints-provisioning
  namespace: monitoring
  labels:
    grafana_alerting: "1"
data:
  contactpoints.yaml: |-
    apiVersion: 1
    contactPoints:
      - orgId: 1
        name: EmailAlerts
        receivers:
          - uid: email_receiver
            type: email
            settings:
              addresses: "test@zarenoff.top"