apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-notification-policies
  namespace: monitoring
  labels:
    grafana_alerting: "1"
data:
  policies.yaml: |-
    apiVersion: 1
    policies:
      - orgId: 1
        receiver: EmailAlerts
        routes:
          - receiver: EmailAlerts
            object_matchers:
              - - "alertname"
                - "=~"
                - ".*"