apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-notification-channels
  namespace: monitoring
  labels:
    grafana_alerting: "1"
data:
  notifiers.yaml: |-
    notifiers:
      - name: EmailAlerts
        type: email
        uid: email1
        is_default: true
        settings:
          addresses: test@zarenoff.top  # Адрес получателя уведомлений