apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    chart: loki
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.29.0
    helm:
      values: |
        loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 1
          storage:
            type: filesystem
          schemaConfig:
            configs:
              - from: 2025-04-01
                object_store: filesystem
                store: tsdb
                schema: v13
                index:
                  prefix: index_
                  period: 24h
          tolerations:
          - key: "node-role"
            operator: "Equal"
            value: "infra"
            effect: "NoSchedule"
          nodeSelector:
            node-role.kubernetes.io/infra: "true"
        singleBinary:
          replicas: 1
          tolerations:
          - key: "node-role"
            operator: "Equal"
            value: "infra"
            effect: "NoSchedule"
          nodeSelector:
            node-role.kubernetes.io/infra: "true"
        deploymentMode: "SingleBinary"
        backend:
          replicas: 0
        read:
          replicas: 0
        write:
          replicas: 0
        chunksCache:
          allocatedMemory: 1024
          tolerations:
          - key: "node-role"
            operator: "Equal"
            value: "infra"
            effect: "NoSchedule"
          nodeSelector:
            node-role.kubernetes.io/infra: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true