apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: https://github.com/ZarenOFF/ZarenOFF_DIPLOMA.git
    targetRevision: HEAD
    path: argocd-apps/infra/logging/logging-config
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true