apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: default
  source:
    chart: metallb
    repoURL: https://metallb.github.io/metallb
    targetRevision: 0.14.9
    helm:
      values: |
        # Конфигурация MetalLB
        configInline:
          address-pools:
           - name: default
             protocol: layer2
             addresses:
             - 10.10.99.105-10.10.99.106
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true