{
 "title": "Online Boutique",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Pods stats",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (phase) (kube_pod_status_phase{namespace=\"boutiqe\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods Restarts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(pod) (kube_pod_container_status_restarts_total{namespace=\"boutiqe\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requested CPU, Core",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (kube_pod_container_resource_requests{namespace=\"boutiqe\", resource=\"cpu\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requested Memory, Mb",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (kube_pod_container_resource_requests{namespace=\"boutiqe\", resource=\"memory\"}/1000000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_network_receive_bytes_total{namespace=\"boutiqe\"}[5m]))",
     "legendFormat": "Input: {{pod}}"
    },
    {
     "expr": "sum by (pod) (rate(container_network_transmit_bytes_total{namespace=\"boutiqe\"}[5m]))",
     "legendFormat": "Output: {{pod}}"
    }
   ]
  }
 ]
}