apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    chart: metallb
    repoURL: https://metallb.github.io/metallb
    targetRevision: 0.14.9
    # helm:
    #   values: |
    #     controller:
    #       tolerations:
    #       - key: "node-role"
    #         operator: "Equal"
    #         value: "infra"
    #         effect: "NoSchedule"
    #       nodeSelector:
    #         node-role.kubernetes.io/infra: "true"
    #     speaker:
    #       tolerations:
    #       - key: "node-role"
    #         operator: "Equal"
    #         value: "infra"
    #         effect: "NoSchedule"
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
