apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
  namespace: metallb-system
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  addresses:
  - 10.10.99.105-10.10.99.106
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advertisement
  namespace: metallb-system
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  ipAddressPools:
  - default-pool