loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
  tolerations:
  - key: "node-role"
    operator: "Equal"
    value: "infra"
    effect: "NoSchedule"
  nodeSelector:
    node-role.kubernetes.io/infra: "true"

singleBinary:
  replicas: 1
  tolerations:
  - key: "node-role"
    operator: "Equal"
    value: "infra"
    effect: "NoSchedule"
  nodeSelector:
    node-role.kubernetes.io/infra: "true"