apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-alerts
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  project: default
  source:
    repoURL: https://github.com/ZarenOFF/ZarenOFF_DIPLOMA.git
    targetRevision: HEAD
    path: argocd-apps/infra/monitoring/grafana-alerts-config
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true