apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 70.3.0
    helm:
      releaseName: monitoring
      values: |
        prometheus:
          prometheusSpec:
            storageSpec: null

        grafana:
          adminPassword: null
          #envFromSecret: "grafana-smtp-credentials"
          ingress:
            enabled: false

          #alerting:
          #  enabled: false
          #unifiedAlerting:
          #  enabled: true

          sidecar:
            dashboards:
              enabled: true
              label: grafana_dashboard
              labelValue: "1"
            datasources:
              enabled: true
              label: grafana_datasource
              labelValue: "1"
            alerting:
              enabled: true
              label: grafana_alerts
              labelValue: "1"
              searchNamespace: monitoring

          grafana.ini:
            smtp:
              enabled: "true"
              host: smtp.zarenoff.top:587
              user: test@zarenoff.top
              password: ${SMTP_PASSWORD}
              from_address: test@zarenoff.top
              from_name: Grafana Alerts

        alertmanager:
          enabled: true
          configs:
            global:
              resolve_timeout: 5m
              slack_api_url: "https://test.test/test"
          alertmanagerSpec:
            storage: null

      parameters:
        - name: crds.create
          value: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true