apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 70.3.0
    helm:
      releaseName: monitoring
      values: |
        prometheus:
          prometheusSpec:
            storageSpec: null

        grafana:
          adminPassword: null
          envFromSecret: grafana-smtp-credentials
          ingress:
            enabled: false
          sidecar:
            dashboards:
              enabled: true
            datasources:
              enabled: true
          alerting:
            enabled: true
          unified_alerting:
            enabled: true

          grafana.ini:
            smtp:
              enabled: true
              host: smtp.zarenoff.top:587     # Настройте ваш SMTP сервер и порт
              user: test@zarenoff.top   # SMTP пользователь
              password: ${SMTP_PASSWORD}     # Пароль будет взят из Secret
              from_address: test@zarenoff.top  # Адрес отправителя
              from_name: Grafana Alerts      # Имя отправителя
              ehlo_identity: grafana.zarenoff.top # Имя хоста для EHLO
              starttls_policy: OpportunisticStartTLS  # Политика TLS
            alerting:
              enabled: true
              execute_alerts: true
            unified_alerting:
              enabled: true

        alertmanager:
          alertmanagerSpec:
            storage: null
      parameters:
        - name: crds.create
          value: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true