name: Build and Push Services

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - '.github/workflows/build-and-push.yaml'
      - 'version.txt'

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - adservice
          - cartservice
          - checkoutservice
          - currencyservice
          - emailservice
          - frontend
          - loadgenerator
          - paymentservice
          - productcatalogservice
          - recommendationservice
          - shippingservice
          - shoppingassistantservice

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get current version
        id: version
        run: |
          CURRENT_VERSION=$(cat version.txt)
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV

      - name: Increment version
        run: |
          # Get current version and increment patch number
          IFS='.' read -r major minor patch <<< "${{ env.CURRENT_VERSION }}"
          NEW_VERSION="$major.$minor.$((patch + 1))"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          # Save new version to file
          echo "$NEW_VERSION" > version.txt

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./src/${{ matrix.service }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/${{ matrix.service }}:latest
            ${{ env.DOCKERHUB_USERNAME }}/${{ matrix.service }}:${{ env.NEW_VERSION }}

      - name: Update version in config
        if: matrix.service == 'shoppingassistantservice' # Run only after last service
        run: |
          # Update versions in config
          sed -i "s|us-central1-docker.pkg.dev/google-samples/microservices-demo/.*:v0.10.2|${{ env.DOCKERHUB_USERNAME }}/\1:${{ env.NEW_VERSION }}|g" \
            argocd-apps/apps/boutiqe/boutiqe-config/config.yaml

      - name: Commit and push if changed
        if: matrix.service == 'shoppingassistantservice' # Run only after last service
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          git add version.txt
          git add argocd-apps/apps/boutiqe/boutiqe-config/config.yaml
          
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update service versions to ${{ env.NEW_VERSION }}"
            git push
          fi